
# establish the script directory absolute path

SCRIPT_NAME=${BASH_SOURCE[0]}
SCRIPT_DIR=`dirname ${SCRIPT_NAME}`
ORIGINAL_DIR=${PWD}
cd $SCRIPT_DIR
SCRIPT_DIR=`pwd`
cd $ORIGINAL_DIR

# aliases

alias count=${SCRIPT_DIR}/count.sh
alias oval=${SCRIPT_DIR}/oval.py

# user scripts

if [ -r ${HOME}/.profile ]
then
  source ${HOME}/.profile
fi

# prompt

PS1="${DTAG#*/}:\w> "
